name: Update IPTV List

on:
  schedule:
    # Hər 6 saatdan bir işləyəcək (Cron formatı)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Lazım olanda əllə başlatmaq üçün

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_link.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git commit -m "Auto-update IPTV link with new token" || echo "No changes to commit"
          git push
