name: Update IPTV

on:
  schedule:
    - cron: "0 */6 * * *" # Hər 6 saatdan bir
  workflow_dispatch: # İstədiyin vaxt manual başlatmaq üçün

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run scripts
        run: |
          python update_aze.py
          python update_tr.py

      - name: Commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Hər iki m3u faylını əlavə edirik
          git add Aze.m3u Tur.m3u
          
          git commit -m "Auto update IPTV (AZE & TR): $(date)" || exit 0
          git push
